function u = nonlin_el(x, X, t, n, x0, dof, P, mat_type,...
                        shape_type, load_type, max_tol, n_ints)
    u = newton(x, X, t, n, x0, dof, P,mat_type, ...
               shape_type, load_type, max_tol,  n_ints);
end